environment: development

# General
title: Semanux
description: > # This means to ignore newlines.
  We make the Web inclusive!
email: contact@semanux.com
# Where things are.
source: .
destination: ./_site
plugins_dir: _plugins
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes
sass.sass_dir: _sass
collections:
  posts:
    output: true

# Serving
host: 0.0.0.0 # Means that local development server is accesible from home network. Useful for checking with other devices (e.g. Windows laptop, mobile, etc.)
port: 4000

# Content
draft: false # TODO: Why do we set draft and future to false in development?
future: false
permalink: pretty
markdown: kramdown
defaults:
  -
    scope:
      path: "" # An empty string here means all files in the project.
    values:
      title: "" # Required as fallback before checkinog for localized title.
  # Posts
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: blog/:title
exclude:
  - .gitignore
  - .github
  - .prettierignore
  - .prettierrc.yml
  - .stylelintrc.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - vendor

# Templating system.
liquid:
  error_mode: strict
  strict_variables: true
  strict_filters: true

# SCSS to CSS conversion.
sass:
  style: expanded
  sourcemap: never # Sourcemaps seem to be broken in our Jekyll version. TODO: link GitHub issue for this.

plugins:
  - jekyll-polyglot

# Plugin: Polyglot
languages: ["en", "de"]
default_lang: "en"
exclude_from_localization: ["static"]
parallel_localization: false # Must be false for Windows.
lang_from_path: true
