environment: development

# Where things are
source: .
destination: ./_site
plugins_dir: _plugins
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes
collections:
  posts:
    output: true

# Defaults for front matters
defaults:
  - # posts
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: blog/:title

# General project settings
title: Semanux
email: contact@semanux.com
description: > # this means to ignore newlines
  We make the Web inclusive!
plugins: [jekyll-polyglot]
baseurl: "" # must be empty string
markdown: kramdown
permalink: pretty
future: false # TODO: set to true to see future posts
exclude:
  - README.md
  - /*README.md
  - .gitignore
  - .github
  - vendor
  - Gemfile
  - Gemfile.lock
liquid:
  strict_variables: true
  strict_filters: true

# Deployment
host: 0.0.0.0
port: 4000

# Sass settings
sass:
  sass_dir: _sass
  sourcemap: never # Sourcemaps seem to be broken in our Jekyll version (TODO: link GitHub for this).

# Polyglot settings
languages: ["en", "de"]
default_lang: "en"
exclude_from_localization: ["static", "css", "assets"]
parallel_localization: false # must be false for Windows
lang_from_path: true

# Misc
misc:
  en: English
  de: Deutsch
