baseURL = "https://semanux.com/"
languageCode = "en-us"
title = "Semanux"
ignoreFiles = [ "\\.gitkeep$" ] # does not work yet (https://github.com/gohugoio/hugo/issues/4874)

DefaultContentLanguage = "en"
# defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1
  [languages.de]
    languageName = "German"
    languageCode = "de-de"
    weight = 2

# Allow HTML in markdown files
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true