name: ci

on:
  push:
    branches:
      - main  # source files for hugo

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: # checkout with submodules (not yet required)
          submodules: true
          fetch-depth: 0

      - name: Setup
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.74.2'
          # extended: true

      - name: Build
        run: hugo --minify
  
      - name: Push    
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "public/"
          target: "/httpdocs/"
